groups:
  - name: system_alerts
    rules:
      # CPU 使用率告警
      - alert: HighCPUUsage
        expr: system_cpu_usage_percent > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "CPU使用率过高"
          description: "系统CPU使用率超过80%，持续5分钟。当前值: {{ $value }}%"

      # 内存使用率告警
      - alert: HighMemoryUsage
        expr: system_memory_usage_percent > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "内存使用率过高"
          description: "系统内存使用率超过85%，持续5分钟。当前值: {{ $value }}%"

      # 磁盘使用率告警
      - alert: HighDiskUsage
        expr: system_disk_usage_percent > 90
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "磁盘使用率过高"
          description: "系统磁盘使用率超过90%，持续5分钟。当前值: {{ $value }}%"

  - name: application_alerts
    rules:
      # HTTP 错误率告警
      - alert: HighHTTPErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "HTTP错误率过高"
          description: "HTTP 5xx错误率超过10%。当前错误率: {{ $value }}"

      # HTTP 请求延迟告警
      - alert: HighHTTPLatency
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "HTTP请求延迟过高"
          description: "95%的HTTP请求延迟超过2秒。当前延迟: {{ $value }}s"

      # WebSocket 连接断开告警
      - alert: WebSocketConnectionDrop
        expr: websocket_active_connections < 1
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "WebSocket连接断开"
          description: "WebSocket连接数量异常下降。当前连接数: {{ $value }}"

  - name: deployment_alerts
    rules:
      # 部署失败告警
      - alert: DeploymentFailed
        expr: deployment_status == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "部署失败"
          description: "检测到部署失败"

      # 部署时间过长告警
      - alert: LongDeploymentTime
        expr: histogram_quantile(0.95, rate(deployment_duration_seconds_bucket[10m])) > 300
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "部署时间过长"
          description: "95%的部署时间超过5分钟。当前平均时间: {{ $value }}s"

  - name: service_alerts
    rules:
      # 服务不可用告警
      - alert: ServiceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "服务不可用"
          description: "服务 {{ $labels.instance }} 不可用"

      # 目标不可达告警
      - alert: TargetUnreachable
        expr: up == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "监控目标不可达"
          description: "监控目标 {{ $labels.instance }} 不可达"

  - name: database_alerts
    rules:
      # MySQL 连接数告警
      - alert: HighMySQLConnections
        expr: mysql_global_status_threads_connected > 100
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "MySQL连接数过高"
          description: "MySQL连接数超过100。当前连接数: {{ $value }}"

      # Redis 内存使用率告警
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Redis内存使用率过高"
          description: "Redis内存使用率超过80%。当前使用率: {{ $value }}%"

  - name: infrastructure_alerts
    rules:
      # 黑盒监控失败告警
      - alert: BlackboxProbeFailed
        expr: probe_success == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "服务探测失败"
          description: "服务 {{ $labels.instance }} 探测失败"

      # 黑盒监控延迟告警
      - alert: BlackboxProbeSlow
        expr: probe_duration_seconds > 2
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "服务响应缓慢"
          description: "服务 {{ $labels.instance }} 响应时间超过2秒。当前延迟: {{ $value }}s"
